api_version = "2026-01"

[[extensions]]
name = "Volume Discount Function"
handle = "discount-function"
type = "function"
uid = "630829f6-2180-df6b-6a08-656aa871d3f31c3e344a"
description = "Applies a percentage discount when customer buys 2 or more of configured products"

  [[extensions.targeting]]
  target = "cart.lines.discounts.generate.run"
  input_query = "src/cart_lines_discounts_generate_run.graphql"
  export = "cart-lines-discounts-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"
